version: '3.8'

services:
  startapp-mysql:
    image: mysql:8
    container_name: startapp-mysql
    ports:
      - 13306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./db/mysql:/var/lib/mysql
  startapp-redis:
    image: redis:alpine
    container_name: startapp-redis
    ports:
      - 6379:6379
    restart: on-failure
  startapp-qa:
    container_name: startapp-qa
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - startapp-mysql
      - startapp-redis
    restart: on-failure