version: '3.8'

services:
  startapp-mysql-dev:
    image: mysql:8
    container_name: startapp-mysql-dev
    ports:
      - 13306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .dev-env
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      startapp-dev-network:
  startapp-redis-dev:
    image: redis:alpine
    container_name: startapp-redis-dev
    ports:
      - 16379:6379
    restart: on-failure
    networks:
      startapp-dev-network:

networks:
  startapp-dev-network:
    external: true
    name: startappnet